export const AUTH_TEST_IDS = {
  EMAIL_INPUT: "login-email-input",
  PASSWORD_INPUT: "login-password-input",
  SIGN_IN_BUTTON: "login-signin-btn",
  SIGN_UP_BUTTON: "login-signup-btn",
  GOOGLE_BUTTON: "login-google-btn",
  EMAIL_BUTTON: "login-email-btn",
  SIGNUP_NAME: "signup-name-input",
  SIGNUP_EMAIL: "signup-email-input",
  SIGNUP_PASSWORD: "signup-password-input",
  SIGNUP_CONFIRM_PASSWORD: "signup-confirm-password-input",
  FORGOT_LINK: "login-forgot-link",
  FORGOT_EMAIL: "forgot-email-input",
  SEND_RESET: "login-send-reset",
  BACK_TO_SIGNIN: "login-back-to-signin",
  GOTO_SIGNUP: "login-goto-signup",
  GOTO_SIGNIN: "login-goto-signin",
  BRAND_TITLE: "brand-title",
  LOGIN_ERROR: "login-error",
  PHONE_INPUT: "login-phone-input",
  SUBMIT_BUTTON: "login-submit-button",
};
