/*
# Create otp_codes table for self-contained Email OTP authentication

## Purpose
Stores 6-digit one-time passwords generated by the email-otp edge function.
This removes the dependency on Supabase's built-in magic link email delivery
and gives full control over OTP generation, expiry, and resend cooldown.

## New Tables
- `otp_codes`
  - `id` (uuid, primary key)
  - `email` (text, indexed) — the email address the OTP was sent to
  - `code_hash` (text) — SHA-256 hash of the 6-digit code (never store raw)
  - `expires_at` (timestamptz) — when the OTP expires (5 minutes from creation)
  - `resend_available_at` (timestamptz) — earliest time a new OTP can be requested (30s)
  - `verified` (boolean, default false) — whether this OTP was successfully used
  - `attempts` (int, default 0) — number of failed verification attempts
  - `created_at` (timestamptz, default now())

## Security
- RLS enabled. Only the service role (edge function) can read/write.
  The anon key cannot access this table directly — all access goes through
  the edge function which uses the service role key internally.
- No SELECT/INSERT/UPDATE/DELETE policies for anon or authenticated roles,
  so the table is locked to all non-service-role access.
*/

CREATE TABLE IF NOT EXISTS otp_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  resend_available_at timestamptz NOT NULL,
  verified boolean NOT NULL DEFAULT false,
  attempts int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_otp_codes_email ON otp_codes (email);
CREATE INDEX IF NOT EXISTS idx_otp_codes_expires_at ON otp_codes (expires_at);

ALTER TABLE otp_codes ENABLE ROW LEVEL SECURITY;
